image: node:14.18.1

variables:
  IMAGE_BASE_NAME: ${CI_REGISTRY}/seller-fulfillment
  DEV_LATEST: $CI_REGISTRY/seller-fulfillment:latest
  PROD_LATEST: $CI_REGISTRY/seller-fulfillment:prod
stages:
  - lint
  - test
  - docker
  - deploy

eslint:
  stage: lint
  tags:
    - docker
  script:
    - npm i eslint
    - npm run lint

test:
  image: cypress/base:14.16.0
  stage: test
  tags:
    - docker
  cache:
    paths:
      - .npm
      - /root/.cache/Cypress

  script:
    - npm ci --prefer-offline
    - npx cypress cache path
    - npx cypress cache list
    - npm run test

docker_build:
  stage: docker
  tags:
    - shell 
  script:
    - |
      if [ "$CI_COMMIT_REF_NAME" == "master" ]
      then 
        IMAGE_TAG=prod_$(date +%Y-%m-%d-%H-%M)
        IMAGE_NAME=${IMAGE_BASE_NAME}:${IMAGE_TAG}
        docker build -t $IMAGE_NAME -t $PROD_LATEST
          --build-arg VUE_APP_GOOGLE_API_KEY="AIzaSyBr3G1ZoEidlWAw_NOO11NZsVidPuF6zeo"
          --build-arg VUE_APP_GOOGLE_API_KEY_TEST="AIzaSyC4UV3vk4qedVcCXDdpY7ZBNb4IQAM4vY8"
          --build-arg VUE_APP_GOOGLE_CLIENT_ID="724697801657-96bbmn0plsro60t4rg2eekvnbfrfnqvb.apps.googleusercontent.com"
          --build-arg VUE_APP_VAPIDKEY="BGNlgSsJAfNM7suOwAm0LyVX7H5GCB9lUosFfOQy99Qrhr7fpPGE2xd5h7qekXL0WYwIf2K26CCMz3wWMiG49jY"
          --build-arg VUE_APP_ALGOLIA_APP_ID="YGZO0B7NVS"
          --build-arg VUE_APP_ALGOLIA_API_KEY="d19d556ce4b0b3897d5c8956e43428c2"
          --build-arg VUE_APP_ALGOLIA_INDEX_NAME="production_fulfillment"  .
        docker push $IMAGE_NAME 
        docker push $PROD_LATEST
      elif [ "$CI_COMMIT_REF_NAME" == "staging" ]
      then 
        IMAGE_TAG=dev_$(date +%Y-%m-%d-%H-%M)
        IMAGE_NAME=${IMAGE_BASE_NAME}:${IMAGE_TAG}
        docker build -t $IMAGE_NAME -t $DEV_LATEST  
          --build-arg VUE_APP_GOOGLE_API_KEY="AIzaSyBr3G1ZoEidlWAw_NOO11NZsVidPuF6zeo"
          --build-arg VUE_APP_GOOGLE_API_KEY_TEST="AIzaSyC4UV3vk4qedVcCXDdpY7ZBNb4IQAM4vY8"
          --build-arg VUE_APP_GOOGLE_CLIENT_ID="724697801657-96bbmn0plsro60t4rg2eekvnbfrfnqvb.apps.googleusercontent.com"
          --build-arg VUE_APP_VAPIDKEY="BGNlgSsJAfNM7suOwAm0LyVX7H5GCB9lUosFfOQy99Qrhr7fpPGE2xd5h7qekXL0WYwIf2K26CCMz3wWMiG49jY"
          --build-arg VUE_APP_ALGOLIA_APP_ID="YGZO0B7NVS"
          --build-arg VUE_APP_ALGOLIA_API_KEY="d19d556ce4b0b3897d5c8956e43428c2"
          --build-arg VUE_APP_ALGOLIA_INDEX_NAME="staging_fulfillment"  .
        docker push $DEV_LATEST
        docker push $IMAGE_NAME
      else
        export IMAGE_NAME="sendy-docker-local.jfrog.io/seller-fulfillment:$(echo $CI_COMMIT_REF_NAME | awk -F "/" '{ print $2 }')_$(date +%Y-%m-%d-%H-%M)"
        docker build -t $IMAGE_NAME . 
      fi
      docker push $IMAGE_NAME
  only:
    - staging
    - master
    - /^feature*.*$/


create-preview-env:
  stage: deploy
  tags:
    - manta
  before_script:
    - export FEATURE="$(echo $CI_COMMIT_REF_NAME | awk -F "/" '{ print $2 }')"
  script:
    - pwd
    - source ~/.bash_profile && /opt/manta -c $FEATURE -f /home/ubuntu/.kube/config
  only:
    refs:
      - /^feature*.*$/
