export default {
  getMobile: (state) => state.mobile,
  getComponent: (state) => state.component,
  getExternal: (state) => state.external,
  getTab: (state) => state.tab,
  getLoader: (state) => state.loader,
  getOrderTimelines: (state) => state.orderTimelines,
  getRescheduledOrderTimelines: (state) => state.rescheduledOrderTimelines,
  getOrderEvents: (state) => state.orderEvents,
  getData: (state) => state.data,
  getOrderStatuses: (state) => state.orderStatuses,
  getDeliveries: (state) => state.deliveries,
  getDeliveryInfo: (state) => state.deliveryInfo,
  getProducts: (state) => state.products,
  getOverlay: (state) => state.overlay,
};
