export default {
  getMobile: (state) => state.mobile,
  getComponent: (state) => state.component,
  getExternal: (state) => state.external,
  getTab: (state) => state.tab,
  getLoader: (state) => state.loader,
  getOrderTimelines: (state) => state.orderTimelines,
  getRescheduledOrderTimelines: (state) => state.rescheduledOrderTimelines,
  getOrderEvents: (state) => state.orderEvents,
  getData: (state) => state.data,
  getOrderStatuses: (state) => state.orderStatuses,
  getDeliveries: (state) => state.deliveries,
  getDeliveryInfo: (state) => state.deliveryInfo,
  getPickupInfo: (state) => state.pickupInfo,
  getProducts: (state) => state.products,
  getOverlay: (state) => state.overlay,
  getStatements: (state) => state.statements,
  getInvoices: (state) => state.invoices,
  getInvoiceContent: (state) => state.invoiceContent,
  getTotalDue: (state) => state.totalDue,
  getTransationHistory: (state) => state.transationHistory,
  getUsers: (state) => state.users,
  getLanguages: (state) => state.languages,
  getDefaultLanguage: (state) => state.defaultLanguage,
  getDownloadActions: (state) => state.downloadActions,
  getDeliveryActions: (state) => state.deliveryActions,
  getActivityLog: (state) => state.activityLog,
};
