import { createStore } from "vuex";
import actions from "./actions";
import getters from "./getters";
import mutations from "./mutations";
import { shallowRef } from "vue";
import { Check, Minus } from "@element-plus/icons-vue";

export default createStore({
  namespaced: true,
  state() {
    return {
      mobile: false,
      component: "common.dashboard",
      languages: [
        {
          title: "English",
          value: "en",
        },
        {
          title: "French",
          value: "fr",
        },
      ],
      exportDataType: "",
      parent: "",
      editValue: "inventory",
      defaultLanguage: "en",
      mappedSelectedProducts: [],
      external: [
        "/auth/",
        "/auth/sign-in",
        "/auth/sign-up",
        "/auth/otp",
        "/auth/complete-signup",
        "/external/invite",
      ],
      deliverySpeed: [
        {
          local_order_uuid: "42757fc9-ffee-40ba-b965-a493731e9957",
          proposed_speeds: [
            {
              local_order_uuid: "42757fc9-ffee-40ba-b965-a493731e9957",
              speed_pricing_type: "SENDY_SAME_DAY",
              transport_provider: "SENDY",
              speed_pricing_uuid: "194e60a6-a030-46db-871a-f715e6345ed1",
              speed_pricing_description: "",
              price: 0.0,
              currency: "KES",
              speed_pricing_lower_limit_date: 1671191937000,
              speed_pricing_upper_limit_date: 1671227937000,
              pricing_expiration_date: 1671278337000,
            },
            {
              local_order_uuid: "42757fc9-ffee-40ba-b965-a493731e9957",
              speed_pricing_type: "SENDY_NEXT_DAY",
              transport_provider: "SENDY",
              speed_pricing_uuid: "239b4b88-add3-4d54-aada-2dab2836c475",
              speed_pricing_description: "",
              price: 0.0,
              currency: "KES",
              speed_pricing_lower_limit_date: 1671191937000,
              speed_pricing_upper_limit_date: 1671278337000,
              pricing_expiration_date: 1671278338000,
            },
            {
              local_order_uuid: "42757fc9-ffee-40ba-b965-a493731e9957",
              speed_pricing_type: "SENDY_SCHEDULED",
              transport_provider: "SENDY",
              speed_pricing_uuid: "77f6ffa2-4037-4f81-bb59-14d1f61a4997",
              speed_pricing_description: "",
              price: 0.0,
              currency: "KES",
              speed_pricing_lower_limit_date: 1671191937000,
              speed_pricing_upper_limit_date: 1671623937000,
              pricing_expiration_date: 1671278338000,
            },
          ],
        },
      ],
      pickUpSpeed: [
        {
          local_order_uuid: "42757fc9-ffee-40ba-b965-a493731e9957",
          proposed_speeds: [
            {
              local_order_uuid: "42757fc9-ffee-40ba-b965-a493731e9957",
              speed_pricing_type: "SENDY_SAME_DAY",
              transport_provider: "SENDY",
              speed_pricing_uuid: "194e60a6-a030-46db-871a-f715e6345ed1",
              speed_pricing_description: "",
              price: 0.0,
              currency: "KES",
              speed_pricing_lower_limit_date: 1671191937000,
              speed_pricing_upper_limit_date: 1671227937000,
              pricing_expiration_date: 1671278337000,
            },
            {
              local_order_uuid: "42757fc9-ffee-40ba-b965-a493731e9957",
              speed_pricing_type: "SENDY_NEXT_DAY",
              transport_provider: "SENDY",
              speed_pricing_uuid: "239b4b88-add3-4d54-aada-2dab2836c475",
              speed_pricing_description: "",
              price: 0.0,
              currency: "KES",
              speed_pricing_lower_limit_date: 1671191937000,
              speed_pricing_upper_limit_date: 1671278337000,
              pricing_expiration_date: 1671278338000,
            },
            {
              local_order_uuid: "42757fc9-ffee-40ba-b965-a493731e9957",
              speed_pricing_type: "SENDY_SCHEDULED",
              transport_provider: "SENDY",
              speed_pricing_uuid: "77f6ffa2-4037-4f81-bb59-14d1f61a4997",
              speed_pricing_description: "",
              price: 0.0,
              currency: "KES",
              speed_pricing_lower_limit_date: 1671191937000,
              speed_pricing_upper_limit_date: 1671623937000,
              pricing_expiration_date: 1671278338000,
            },
          ],
        },
      ],
      mismatchedDates: false,
      tabStatuses: {
        All: "",
        Pending: "ORDER_RECEIVED,ORDER_IN_PROCESSING",
        inTransit: "ORDER_IN_TRANSIT",
        Failed: "ORDER_FAILED",
        Completed: "ORDER_COMPLETED",
        Cancelled: "ORDER_CANCELED",
      },
      pagination: {
        current_page: 0,
        max: 5,
        page_count: 5,
      },
      supportedCountries: [],
      geofenceData: [],
      userData: {},
      updatedData: {},
      confirmedUser: {},
      businessUserDetails: {},
      googleUserData: {},
      industries: {},
      countries: {},
      errors: {},
      loginData: {},
      googleConfirmData: {},
      session: {},
      editedDocuments: [],
      signUpwithGoogle: false,
      OTPRedirectUrl: "",
      allProductCount: 0,
      archivedProductCount: 0,
      accessToken: localStorage.getItem("accessToken"),
      refreshToken: "",
      productStep: 0,
      tabStatus: "",
      documentURL: "",
      addProductStatus: false,
      paymentCollectionStatus: {
        amountToBeCollected: "",
        deliveryFee: "",
      },
      wallets: [
        {
          wallet_type: "test data",
          wallet_description: "Seller's Wallet",
          wallet_balance: 0.0,
          wallet_maximum_withdraw_amount: 0.0,
          wallet_minimum_withdraw_amount: 33,
          wallet_withdraw_fees: 33,
          currency: "KES",
        },
      ],
      signMapping: {
        EARNING_FROM_SALE_OF_GOOD: "+",
        EARNING_FROM_WITHDRAWAL_REFUND: "+",
        FULFILMENT_FEE_PAYMENT: "+",
        UPCOMING_EARNING_FROM_SALE_OF_GOOD: "+",
        WITHDRAWAL_OF_EARNING: "-",
        FULFILMENT_FEE_COST: "-",
        WITHDRAWAL_OF_EARNING_COST: "-",
      },
      pickUpOptions: {
        type: "driver",
        text: "inventory.sendDriverToPickTheItems",
        info: "",
        date: "",
        FC: "",
      },
      pickUpStation: "",
      stations: [
        {
          name: "Sendy Marsabit Plaza FC",
          location: "Marsabit Plaza, Ngong road",
          room: "1st floor, Rm 101",
          hours: "9:00 AM to 6:00 PM",
        },
        {
          name: "Sendy Marsabit Plaza FC",
          location: "Marsabit Plaza, Ngong road",
          room: "1st floor, Rm 101",
          hours: "9:00 AM to 6:00 PM",
        },
        {
          name: "Sendy Marsabit Plaza FC",
          location: "Marsabit Plaza, Ngong road",
          room: "1st floor, Rm 101",
          hours: "9:00 AM to 6:00 PM",
        },
        {
          name: "Sendy Marsabit Plaza FC",
          location: "Marsabit Plaza, Ngong road",
          room: "1st floor, Rm 101",
          hours: "9:00 AM to 6:00 PM",
        },
      ],
      searchedProducts: [],
      transactionTypes: [
        {
          name: "payments.all",
          value: "ALL",
        },
        {
          name: "payments.paymentCollection",
          value: "EARNING_FROM_SALE_OF_GOOD,UPCOMING_EARNING_FROM_SALE_OF_GOOD",
        },
        {
          name: "payments.refundForWithdrawal",
          value: "EARNING_FROM_WITHDRAWAL_REFUND",
        },
        {
          name: "payments.paymentOfFulfilmentFees",
          value: "FULFILMENT_FEE_PAYMENT",
        },
        {
          name: "payments.withdrawal",
          value: "WITHDRAWAL_OF_EARNING",
        },
        {
          name: "payments.invoiceForFulfilmentServices",
          value: "FULFILMENT_FEE_COST",
        },
        {
          name: "payments.withdrawalFee",
          value: "WITHDRAWAL_OF_EARNING_COST",
        },
      ],
      statisticsStats: {
        currency: "KES",
        transaction_type_count: 0,
        transaction_type_total_value: 0,
      },
      activeTransaction: {
        date_created: 1666779480000,
        resource_id: "D-KKBNV-00000",
        transaction_amount: 93,
        transaction_currency: "KES",
        transaction_description: "Payment Collection",
        transaction_id: "UPCOMING_EARNING_FROM_SALE_OF_GOOD-000000",
        transaction_subtitle: "Delivery to Seme",
        transaction_type: "UPCOMING_EARNING_FROM_SALE_OF_GOOD",
      },
      transactions: [
        {
          date_created: 1666604638000,
          transaction_id: "EARNING_FROM_SALE_OF_GOOD-00000",
          transaction_type: "EARNING_FROM_SALE_OF_GOOD",
          transaction_description: "Payment Collection",
          transaction_subtitle: "Delivery to Customer",
          transaction_currency: "KES",
          transaction_amount: 12,
          resource_id: "D-MIBVF-00000",
        },
        {
          date_created: 1666598759000,
          transaction_id: "EARNING_FROM_WITHDRAWAL_REFUND-00000",
          transaction_type: "EARNING_FROM_WITHDRAWAL_REFUND",
          transaction_description: "Refund for Withdrawal",
          transaction_subtitle: null,
          transaction_currency: "KES",
          transaction_amount: 53,
          resource_id: null,
        },
        {
          date_created: 1666598745000,
          transaction_id: "WITHDRAWAL_OF_EARNING-00000",
          transaction_type: "WITHDRAWAL_OF_EARNING",
          transaction_description: "Withdrawal via MPESA",
          transaction_subtitle: "5c6c11b5-1335-4eb8-95c2-0000000",
          transaction_currency: "KES",
          transaction_amount: 20,
          resource_id: "WI-EIBC-0000",
        },
        {
          date_created: 1666598745000,
          transaction_id: "WITHDRAWAL_OF_EARNING_COST-000000",
          transaction_type: "WITHDRAWAL_OF_EARNING_COST",
          transaction_description: "Withdrawal Fee for KES 20.0",
          transaction_subtitle: null,
          transaction_currency: "KES",
          transaction_amount: 33,
          resource_id: null,
        },
        {
          date_created: 1666598313000,
          transaction_id: "EARNING_FROM_WITHDRAWAL_REFUND-000000",
          transaction_type: "EARNING_FROM_WITHDRAWAL_REFUND",
          transaction_description: "Refund for Withdrawal",
          transaction_subtitle: null,
          transaction_currency: "KES",
          transaction_amount: 43,
          resource_id: null,
        },
      ],
      terms: {
        KE: "https://www.sendyit.com/fulfillment-terms-conditions",
        NG: "https://www.sendyit.com/nigeria/fulfillment-terms-conditions",
        CI: "https://www.sendyit.com/cote-divoire/fulfillment-terms-conditions",
        UG: "https://www.sendyit.com/ug/fulfillment-terms-conditions",
      },
      downloadActions: [
        {
          label: "Excel",
        },
        {
          label: "PDF",
        },
      ],
      mapOptions: {
        componentRestrictions: {
          country: ["ke", "ug", "ci", "ng"],
        },
        bounds: {
          north: 35.6,
          east: 59.4,
          south: -28.3,
          west: -19.1,
        },
        strictBounds: true,
      },
      orderTrackingData: {
        order: {
          order_id: "C-JQM-0000",
          erp_document_number: "FF-00000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644567439000,
          updated_date: 1647870724000,
          order_event_status:
            "event.pickup.partner.submitted.items.at.hub.confirmed.via.code",
          business_id: "B-XGS-1542",
          scheduled_date: 1644567439000,
          completed_date: null,
          confirmation_pin: null,
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-YCZ-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: -0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-NFZ-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "MPESA",
              means_of_payment_id: null,
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "MPESA",
            means_of_payment_id: null,
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: null,
          handshake_policy: null,
          rejection_policy: null,
        },
      },
      defaultCountryCode: "KE",
      defaultCountryName: "KENYA",
      sendyPhoneProps: {
        mode: "international",
        defaultCountry: "ke",
        preferredCountries: ["ke", "ug", "tz"],
      },
      vueTelInputProps: {
        disabledFetchingCountry: false,
        disabled: false,
        disabledFormatting: false,
        placeholder: "Enter phone number",
        required: false,
        enabledCountryCode: false,
        enabledFlags: true,
        autocomplete: "off",
        name: "telephone",
        maxLen: 25,
        dropdownOptions: {
          disabledDialCode: false,
        },
        inputOptions: {
          showDialCode: false,
        },
      },
      deliveryActions: [
        {
          label: "deliveries.getDeliveryCode",
          trigger: false,
          popup: "code",
          show: true,
        },
        {
          label: "deliveries.rescheduleOrder",
          trigger: false,
          popup: "reschedule",
          show: true,
          icon: "mdi mdi-clock-outline",
        },
        {
          label: "deliveries.cancelOrder",
          trigger: false,
          popup: "cancel",
          show: true,
          icon: "mdi mdi-close-circle-outline",
        },
      ],
      overlayStatus: {
        overlay: false,
        popup: "",
        popText: "",
        editStatus: false,
      },
      tab: "All",
      loader: {
        orderTracking: "loading-text",
        deliveries: "loading-text",
        consignments: "loading-text",
        orderTimeline: "loading-text",
        products: "loading-text",
        productDetails: "loading-text",
        calculateFee: "loading-text",
        invoices: "loading-text",
        billingCycles: "loading-text",
        pendingPayment: "loading-text",
        cycleLineItems: "loading-text",
        userDetails: "loading-text",
        users: "loading-text",
        statistics: "loading-text",
        logs: "loading-text",
        transactions: "loading-text",
        dpp: "loading-text",
        pickUpDetails: "loading-text",
        speed: "loading-text",
      },
      overlay: false,
      userChanged: false,
      rangeChanged: false,
      businessUsers: {},
      activityLog: [
        {
          created_date: 1658906290000,
          user_name: "James Doe",
          user_action_type: "PRODUCT_VARIANT_NAME_CHANGED",
          before_value: "Red",
          after_value: "Shear Butter",
          resource_short_description: "Shear Buttter-Shear Buttter",
        },
        {
          created_date: 1658906290000,
          user_name: "Mary Monroe",
          user_action_type: "PRODUCT_VARIANT_ADDED",
          before_value: "Red",
          after_value: "Shear Butter",
          resource_short_description: "Shear Buttter-Shear Buttter",
        },
        {
          created_date: 1658906290000,
          user_name: "James Doe",
          user_action_type: "PRODUCT_VARIANT_ADDED",
          before_value: "Red",
          after_value: "Shear Butter",
          resource_short_description: "Shear Buttter-Shear Buttter",
        },
      ],
      notificationPreferences: [],
      users: [
        {
          user_id: "U-LSH-0000",
          first_name: "First",
          last_name: "Name",
          user_role: "ROLE_OWNER",
          invitation_status: null,
          active_status: null,
          phone_number: "+254 795 000000",
          email: "user@sendyit.com",
          user_access_permissions: [
            {
              permission_id: "CAN_ACCESS_PRODUCTS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_PRODUCTS",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_DELIVERIES_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_DELIVERIES",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_CONSIGNMENTS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_CONSIGNMENTS",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_BILLING_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_PAYMENT_OPTIONS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_MANAGE_USERS_MODULE",
              permission_granted: true,
            },
          ],
        },
        {
          user_id: "U-LSH-0000",
          first_name: "First",
          last_name: "Name",
          user_role: "ROLE_OWNER",
          invitation_status: null,
          active_status: null,
          phone_number: "+254 795 000000",
          email: "user@sendyit.com",
          user_access_permissions: [
            {
              permission_id: "CAN_ACCESS_PRODUCTS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_PRODUCTS",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_DELIVERIES_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_DELIVERIES",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_CONSIGNMENTS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_CONSIGNMENTS",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_BILLING_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_PAYMENT_OPTIONS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_MANAGE_USERS_MODULE",
              permission_granted: true,
            },
          ],
        },
        {
          user_id: "U-LSH-0000",
          first_name: "First",
          last_name: "Name",
          user_role: "ROLE_OWNER",
          invitation_status: null,
          active_status: null,
          phone_number: "+254 795 000000",
          email: "user@sendyit.com",
          user_access_permissions: [
            {
              permission_id: "CAN_ACCESS_PRODUCTS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_PRODUCTS",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_DELIVERIES_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_DELIVERIES",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_CONSIGNMENTS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_CREATE_CONSIGNMENTS",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_BILLING_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_PAYMENT_OPTIONS_MODULE",
              permission_granted: true,
            },
            {
              permission_id: "CAN_ACCESS_MANAGE_USERS_MODULE",
              permission_granted: true,
            },
          ],
        },
      ],
      user: {
        user_id: "U-LSH-0000",
        first_name: "User",
        last_name: "Name",
        user_role: "ROLE_OWNER",
        invitation_status: null,
        active_status: null,
        phone_number: "+254 795 000000",
        email: "user@sendyit.com",
        user_access_permissions: [
          {
            permission_id: "CAN_ACCESS_PRODUCTS_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_CREATE_PRODUCTS",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_DELIVERIES_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_CREATE_DELIVERIES",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_CONSIGNMENTS_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_CREATE_CONSIGNMENTS",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_BILLING_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_PAYMENT_OPTIONS_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_MANAGE_USERS_MODULE",
            permission_granted: true,
          },
        ],
      },
      userAction: "",
      activeUser: {},
      userActions: [
        {
          label: "settings.editUser",
          link: "/settings/edit-user",
          trigger: "",
        },
        {
          label: "settings.activateUser",
          link: "",
          trigger: "activateUser",
        },
        {
          label: "settings.deactivateUser",
          link: "",
          trigger: "deactivateUser",
        },
        {
          label: "settings.resendEmail",
          link: "",
          trigger: "resendEmail",
        },
        {
          label: "settings.modifyPermissions",
          link: "/settings/user-permissions",
          trigger: "",
        },
        {
          label: "settings.viewUser",
          link: "/settings/view-user",
          trigger: "",
        },
      ],
      userAccessPermissions: {
        CAN_ACCESS_PRODUCTS_MODULE: {
          route: [
            "/inventory/products",
            "/inventory/stock-levels",
            "/inventory/view-product",
          ],
        },
        CAN_CREATE_PRODUCTS: {
          route: [
            "/inventory/add-product",
            "/inventory/edit-product",
            "/inventory/import-products",
          ],
        },
        CAN_ACCESS_DELIVERIES_MODULE: {
          route: ["/deliveries/customer", "/deliveries/tracking"],
        },
        CAN_CREATE_DELIVERIES: {
          route: [
            "/inventory/create-delivery",
            "/inventory/add-delivery-products",
            "/inventory/add-delivery-quantities",
          ],
        },
        CAN_ACCESS_CONSIGNMENTS_MODULE: {
          route: ["/deliveries/sendy", "/deliveries/tracking"],
        },
        CAN_CREATE_CONSIGNMENTS: {
          route: [
            "/inventory/create-pickup",
            "/inventory/add-pickup-products",
            "/inventory/add-pickup-quantities",
          ],
        },
        CAN_ACCESS_BILLING_MODULE: {
          route: [
            "/payments/payment-summary",
            "/payments/transactions",
            "/payments/withdraw",
          ],
        },
        CAN_ACCESS_PAYMENT_OPTIONS_MODULE: {
          route: ["/payment-option-page", "/settings/payment-options"],
        },
        CAN_ACCESS_MANAGE_USERS_MODULE: {
          route: [
            "/settings/manage-users",
            "/settings/add-user",
            "/settings/edit-user",
            "/settings/user-permissions",
            "/settings/view-user",
            "/settings/confirm-user-details",
          ],
        },
        CAN_ACCESS_USER_ACTION_LOG: {
          route: ["/settings/activity-log"],
        },
        CAN_EDIT_BUSINESS_PROFILE: {
          route: ["/settings/profile/business-profile"],
        },
      },
      accessDenied: [],
      invoices: [
        {
          created_date: 1636456110000,
          order_completed_date: 1636485362000,
          invoice_id: "IV-BSH-5075",
          order_id: "D-WVJ-1286",
          order_summary: {
            order_recipient_name: "Seme Otoki",
          },
          order_type: "DELIVERY",
          amount: 2,
          currency: "KES",
          applied_rate: 0.2,
          invoice_status: "PAYMENT_SUCCESS",
          invoice_adjustments: [],
          means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "5367-74XX-XXXX-3932",
            participant_type: "SELLER",
            participant_id: "B-AEB-9648",
            meta_data: {},
          },
        },
        {
          created_date: 1655382701000,
          order_completed_date: 1655382734000,
          invoice_id: "IV-UEJ-9936",
          order_id: "D-DWW-6155",
          order_summary: {
            order_recipient_name: "Seme",
          },
          order_type: "DELIVERY",
          amount: 12.6,
          currency: "KES",
          applied_rate: 0.13,
          invoice_status: "PAYMENT_SUCCESS",
          invoice_adjustments: [
            {
              adjustment_type: "COST_OF_FULFILMENT",
              adjustment_description: "KES 0.0 - KES 300.0",
              adjustment_subtitle: null,
              adjustment_value: 12.6,
            },
          ],
          means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "4180-87XX-XXXX-6458",
            participant_type: "SELLER",
            participant_id: "B-AEB-9648",
            meta_data: {},
          },
        },
        {
          created_date: 1655381769000,
          order_completed_date: 1655381828000,
          invoice_id: "IV-KHU-4349",
          order_id: "D-KEH-8449",
          order_summary: {
            order_recipient_name: "Seme",
          },
          order_type: "DELIVERY",
          amount: 20.4,
          currency: "KES",
          applied_rate: 0.13,
          invoice_status: "PAYMENT_SUCCESS",
          invoice_adjustments: [
            {
              adjustment_type: "COST_OF_FULFILMENT",
              adjustment_description: "KES 0.0 - KES 300.0",
              adjustment_subtitle: null,
              adjustment_value: 20.4,
            },
          ],
          means_of_payment: {
            means_of_payment_type: "MPESA",
            means_of_payment_id: null,
            participant_type: "SELLER",
            participant_id: "B-AEB-9648",
            meta_data: {},
          },
        },
      ],
      invoiceContent: [
        {
          customerInfo: {
            customer: "Delivery to James",
            location: "Windsor Heights",
          },
          products: "Shea Butter & 3 other items",
          dateCompleted: "3/1/2022",
          costOfProducts: "KES 400",
          fulfilmentPrice: "KES 54",
        },
        {
          customerInfo: {
            customer: "Delivery to James",
            location: "Umoja momasa apartments",
          },
          products: "Shea Butter & 3 other items",
          dateCompleted: "3/1/2022",
          costOfProducts: "KES 400",
          fulfilmentPrice: "KES 54",
        },
      ],
      transationHistory: [
        {
          details: {
            icon: "mdi-cash-multiple",
            description: "Payment for 2 orders",
          },
          paymentDetails: "Paid via Mpesa.",
          code: "Transaction code; 00000000",
          datePaid: "7/7/2022 11:12 AM",
          amountPaid: "KES 340",
        },
      ],
      totalDue: "KES 54",
      statements: [
        {
          date: "Friday, 19th Jan 2022",
          amount: "",
          items: [
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Pending payment",
              class: "pending",
              price: "- KES 340",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Pending payment",
              class: "pending",
              price: "- KES 300",
            },
            {
              icon: "mdi-warehouse",
              description: "Delivery to fulfillment centre",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Pending payment",
              class: "pending",
              price: "- KES 0",
            },
          ],
        },
        {
          date: "Thursday, 18th Jan 2022",
          amount: "Kes 1,200",
          items: [
            {
              icon: "mdi-cash-multiple",
              description: "Payment for 2 orders",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "+ KES 760",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 300",
            },
            {
              icon: "mdi-warehouse",
              description: "Delivery to fulfillment centre",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 460",
            },
          ],
        },
        {
          date: "Monday, 15th Jan 2022",
          amount: "Kes 1,200",
          items: [
            {
              icon: "mdi-cash-multiple",
              description: "Payment for 2 orders",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "+ KES 340",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 300",
            },
          ],
        },
        {
          date: "Monday, 15th Jan 2022",
          amount: "Kes 1,200",
          items: [
            {
              icon: "mdi-cash-multiple",
              description: "Payment for 2 orders",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "+ KES 340",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 300",
            },
          ],
        },
        {
          date: "Monday, 15th Jan 2022",
          amount: "Kes 1,200",
          items: [
            {
              icon: "mdi-cash-multiple",
              description: "Payment for 2 orders",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "+ KES 340",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 300",
            },
          ],
        },
      ],
      deliveryInfo: {},
      recepientInfo: {},
      pickUpInfoCD: {},
      pickupInfo: {
        location: "Windsor Heights",
        phoneNumber: "+2547000000000",
        instructions: "Come to Windsor",
      },
      products: {
        name: "Shea Butter and 2 other items",
      },
      consignments: [
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
      ],
      deliveries: [
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
      ],
      data: {
        message: "order.retrieve.success",
        data: {
          seller_name: "Some seller",
          order_id: "D-YYK-0000",
          country: "KENYA",
          language: "en",
          consolidated: false,
          order_event_status: "event.delivery.rescheduled.by.sendy",
          order_status: "ORDER_RESCHEDULED",
          order_completion_date: null,
          scheduled_delivery_date: 1651219200000,
          estimated_delivery_date: null,
          confirmation_pin: "0000",
          partner_contact_information: null,
          products: [
            {
              product_name: "Black timberland boots.",
              product_variant_description: "Black timberland boots",
              product_unit_price: 0,
              product_unit_currency: "KES",
              product_image_link:
                "https://s3.eu-west-1.amazonaws.com/sendy-partner-docs/fulfillment_products/B-KBC-5255_1642591764683_image_picker_A5C1AB9A-1D18-4065-BEE7-9ECF2EC6E421-26512-00000DD592078E05.jpg",
              product_unit_count: 2,
            },
            {
              product_name: "Black timberland boots.",
              product_variant_description: "Option 1",
              product_unit_price: 0,
              product_unit_currency: "KES",
              product_image_link:
                "https://s3.eu-west-1.amazonaws.com/sendy-partner-docs/fulfillment_products/B-KBC-5255_1641298024354_image_picker_A053E6C5-E503-4F55-8E35-8CBB8B09B883-25267-00000979B6694B6E.jpg",
              product_unit_count: 2,
            },
          ],
          event_time_line: [
            {
              event_code: "event.delivery.partner.arrived.at.buyer.location",
              event_date: 1636697106000,
              event_notes: null,
            },
            {
              event_code:
                "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
              event_date: 1636697176000,
              event_notes: null,
            },
            {
              event_code: "event.delivery.order.canceled.by.seller",
              event_date: 1636697281000,
              event_notes: null,
            },
            {
              event_code: "event.delivery.failed",
              event_date: 1636698283000,
              event_notes: null,
            },
            {
              event_code: "event.delivery.rescheduled.by.buyer",
              event_date: 1642749240000,
              event_notes: null,
            },
          ],
          destination: {
            name: "Some seller",
            phone_number: "+254700000000",
            delivery_location: {
              description: "Some where",
              longitude: 0.000000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          rated: false,
        },
        errors: [],
      },
      timelineIcons: {
        PAST: {
          icon: shallowRef(Check),
          color: "#EE7D00",
          iconClass: "el-icon-check",
        },
        PRESENT: {
          icon: shallowRef(Minus),
          color: "#EE7D00",
          iconClass: "el-icon-minus",
        },
        FUTURE: {
          hollow: false,
        },
      },
      deliveryAttempts: [
        {
          attempt_index: 1,
          attempt_date: 1654494226000,
          failure_reason: "Damaged Goods",
        },
      ],
      orderTimelines: [
        {
          event_date: 1647870724000,
          event_code: "EVENT_PICKUP_ORDER_CREATED",
          translated_event_code: "summarised.event.pickup.order.created",
          notes: "",
          event_tense: "FUTURE",
          metadata: {},
        },
        {
          event_date: 1647870724000,
          event_code: "EVENT_PICKUP_WAITING_FOR_PARTNER",
          translated_event_code: "summarised.event.pickup.waiting.for.partner",
          notes: "",
          event_tense: "FUTURE",
          metadata: {},
        },
        {
          event_date: 1647870724000,
          event_code: "EVENT_PICKUP_PARTNER_ARRIVED_AT_PICKUP_LOCATION",
          translated_event_code:
            "summarised.event.pickup.partner.arrived.at.pickup.location",
          notes: "",
          event_tense: "FUTURE",
          metadata: {
            shipping_agent: null,
          },
        },
        {
          event_date: 1647870724000,
          event_code:
            "EVENT_PICKUP_PARTNER_SUBMITTED_ITEMS_AT_HUB_CONFIRMED_VIA_CODE",
          translated_event_code:
            "summarised.event.pickup.partner.submitted.items.at.hub.confirmed.via.code",
          notes: null,
          event_tense: "FUTURE",
          metadata: {},
        },
      ],
      dashboardSelectedTab: "dashboard.toYourCustomers",
      inventorySelectedTab: "inventory.all",
      stockSelectedTab: "Overview",
      selectedProducts: [],
      destinations: [
        {
          expanded: 1,
          preferences: false,
          POD: {
            amountToBeCollected: "none",
          },
        },
      ],
      edittedDocuments: [],
      finalDocumentsToEdit: [],
      destinationIndex: 0,
      sendProductsRoute: "",
      product: {
        product_id: "P-KXG-0000",
        objectID: "P-KXG-0000",
        product_name: "Item",
        product_description: "Item variant",
        product_main_color: null,
        product_archived: false,
        business_id: "B-XGS-0000",
        product_collection: {
          collection_id: "PC-KST-8857",
          collection_name: null,
        },
        sales_channel_collections: null,
        product_variants: [
          {
            product_variant_id: "PV-JMU-7623",
            business_id: "B-XGS-0000",
            product_id: "P-KXG-0000",
            product_variant_description: "Item",
            product_variant_currency: "KES",
            product_variant_unit_price: 0,
            product_variant_image_link:
              "https://images.sendyit.com/fulfilment/seller/shirts.png",
            product_variant_expiry_date: null,
            product_variant_quantity: 0,
            product_variant_quantity_type: "GRAM",
            product_variant_stock_levels: {
              available: 0,
              quantity_in_inventory: 0,
              quantity_in_sales_orders: 1,
              quantity_held_in_fulfilment_requests: 0,
              last_updated_date: 1655449379000,
            },
            product_variant_archived: false,
          },
        ],
      },
      eventLabels: {
        "event.pickup.order.created": "deliveries.orderPlacedOn",
        "event.pickup.processing.for.pickup": "deliveries.orderPlacedOn",
        "event.pickup.waiting.for.partner": "deliveries.weAreFindingADriver",
        "event.pickup.partner.assigned": "deliveries.weHaveFoundADriver",
        "event.pickup.partner.enroute.to.pickup.location":
          "deliveries.yourDriverIsOnTheWay",
        "event.pickup.partner.arrived.at.pickup.location":
          "deliveries.yourDriverHasArrivedAtYourPickUpLocation",
        "event.pickup.partner.pickup.from.seller.confirmed.via.code":
          "deliveries.yourProductsHaveBeenPicked",
        "event.pickup.partner.enroute.to.hub":
          "deliveries.yourProductsAreOnTheWay",
        "event.pickup.partner.arrived.at.hub":
          "deliveries.yourDriverHasArrivedAtTheFulfillmentCentre",
        "event.pickup.partner.submitted.items.at.hub.confirmed.via.code":
          "deliveries.yourDriverHasDroppedYourProductsAtTheFulfillmentCentre",
        "event.pickup.hub.items.received.at.hub":
          "deliveries.yourProductsHaveBeenReceivedAtTheFulfilmentCentre",
        "event.pickup.order.canceled.by.seller":
          "deliveries.youHaveCancelledThisOrder",
        "event.pickup.order.canceled.by.sendy":
          "deliveries.sendyHasCancelledThisOrder",
        "event.pickup.rescheduled.by.seller":
          "deliveries.youHaveRescheduledThisOrder",
        "event.pickup.rescheduled.by.sendy":
          "deliveries.sendyHasRescheduledThisOrder",
        "event.pickup.failed": "deliveries.sendyFailedToPickUpYourProducts",
        "event.delivery.order.created": "deliveries.orderPlacedOn",
        "event.delivery.at.hub.processing.for.delivery":
          "deliveries.orderPlacedOn",
        "event.delivery.at.hub.waiting.for.partner":
          "deliveries.preparingDelivery",
        "event.delivery.at.hub.partner.assigned":
          "deliveries.yourDeliveryHasBeenPreparedAndAssignedToADriver",
        "event.delivery.partner.enroute.to.hub":
          "deliveries.yourDeliveryHasBeenPreparedAndAssignedToADriver",
        "event.delivery.partner.arrived.at.hub":
          "deliveries.yourDeliveryHasBeenPreparedAndAssignedToADriver",
        "event.delivery.partner.pickup.from.hub.confirmed.via.code":
          "deliveries.yourDeliveryHasBeenPreparedAndAssignedToADriver",
        "event.delivery.partner.enroute.to.buyer.location":
          "deliveries.arrivingSoon",
        "event.delivery.partner.arrived.at.buyer.location":
          "deliveries.theDriverHasArrivedAndIsReadyToDeliverThePackage",
        "event.delivery.buyer.paid.for.goods":
          "deliveries.theBuyerHasPaidForThePackage",
        "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code":
          "deliveries.deliveryCompletedDate",
        "event.delivery.rejected.items.received.at.hub":
          "deliveries.deliveryCompletedOnRejected",
        "event.delivery.failed": "deliveries.yourPackageFailedToBeDelivered",
        "event.delivery.order.canceled.by.seller":
          "deliveries.youCancelledThisOrder",
        "event.delivery.order.canceled.by.sendy":
          "deliveries.sendyCancelledThisOrder",
        "event.delivery.rescheduled.by.seller":
          "deliveries.youRescheduledThisOrderFor",
        "event.delivery.rescheduled.by.sendy":
          "deliveries.sendyRescheduledThisOrderFor",
        "event.delivery.rescheduled.by.buyer":
          "deliveries.theCustomerRescheduledThisOrderFor",
        "event.delivery.added.to.batch": "deliveries.deliveryAddedToBatch",
      },
      activityLogs: {
        "PRODUCT.VARIANT.ADDED": "settings.addedNewProduct",
        "PRODUCT.VARIANT.ARCHIVED": "settings.productArchived",
        "PRODUCT.VARIANT.UNARCHIVED": "settings.productUnarchived",
        "PRODUCT.VARIANT.NAME.CHANGED": "settings.productChanged",
        "PRODUCT.VARIANT.UNIT.OF.MEASURE.CHANGED":
          "settings.productUnitChanged",
        "PRODUCT.VARIANT.IMAGE.LINK.CHANGED":
          "settings.productImageLinkChanged",
        "PRODUCT.VARIANT.PRICE.CHANGED": "settings.productPriceChanged",
        "ORDER.CREATED": "settings.orderCreated",
        "ORDER.CANCELED": "settings.orderCanceled",
        "ORDER.RESCHEDULED": "settings.orderRescheduled",
        "ORDER.LINE.ITEM.QUANTITY.CHANGED": "settings.orderlineItemChanged",
        "ORDER.DESTINATION.HOUSE_LOCATION.CHANGED":
          "settings.orderDestinatioHouseChanged",
        "ORDER.DESTINATION.LATITUDE.CHANGED":
          "settings.orderDestinatioLatitudeChanged",
        "ORDER.DESTINATION.LONGITUDE.CHANGED":
          "settings.orderDestinatioLongitudeChanged",
        "ORDER.DESTINATION.NAME.CHANGED": "settings.orderDestinatioNameChanged",
        "ORDER.PRIMARY.RECIPIENT.NAME.CHANGED":
          "settings.orderPrimaryRecepientChanged",
        "ORDER.PRIMARY.RECIPIENT.PHONE.NUMBER.CHANGED":
          "settings.orderPrimaryRecepientPhoneChanged",
        "ORDER.SECONDARY.RECIPIENT.PHONE_NUMBER.CHANGED":
          "settings.orderSecondaryRecepientPhoneChanged",
        "ORDER.DELIVERY.INSTRUCTIONS.CHANGED":
          "settings.orderInstructionsChanged",
        "USER.CREATED": "settings.userCreated",
        "USER.ACTIVATED": "settings.userActivated",
        "USER.DEACTIVATED": "settings.userDeactivated",
      },
      productLists: [
        {
          product_id: "P-KXG-0000",
          objectID: "P-KXG-0000",
          product_name: "Item",
          product_description: "Item variant",
          product_main_color: null,
          product_archived: false,
          business_id: "B-XGS-0000",
          product_collection: {
            collection_id: "PC-KST-0000",
            collection_name: null,
          },
          sales_channel_collections: null,
          product_variants: [
            {
              product_variant_id: "PV-JMU-0000",
              business_id: "B-XGS-0000",
              product_id: "P-KXG-0000",
              product_variant_description: "Item",
              product_variant_currency: "KES",
              product_variant_unit_price: 0,
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_expiry_date: null,
              product_variant_quantity: 0,
              product_variant_quantity_type: "GRAM",
              product_variant_stock_levels: {
                available: 0,
                quantity_in_inventory: 0,
                quantity_in_sales_orders: 1,
                quantity_held_in_fulfilment_requests: 0,
                last_updated_date: 1655391003000,
              },
              product_variant_archived: false,
            },
          ],
        },
        {
          product_id: "P-KXG-0000",
          objectID: "P-KXG-0000",
          product_name: "Item",
          product_description: "Item variant",
          product_main_color: null,
          product_archived: false,
          business_id: "B-XGS-0000",
          product_collection: {
            collection_id: "PC-KST-0000",
            collection_name: null,
          },
          sales_channel_collections: null,
          product_variants: [
            {
              product_variant_id: "PV-JMU-0000",
              business_id: "B-XGS-0000",
              product_id: "P-KXG-0000",
              product_variant_description: "Item",
              product_variant_currency: "KES",
              product_variant_unit_price: 0,
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_expiry_date: null,
              product_variant_quantity: 0,
              product_variant_quantity_type: "GRAM",
              product_variant_stock_levels: {
                available: 0,
                quantity_in_inventory: 0,
                quantity_in_sales_orders: 1,
                quantity_held_in_fulfilment_requests: 0,
                last_updated_date: 1655391003000,
              },
              product_variant_archived: false,
            },
          ],
        },
        {
          product_id: "P-KXG-0000",
          objectID: "P-KXG-0000",
          product_name: "Item",
          product_description: "Item variant",
          product_main_color: null,
          product_archived: false,
          business_id: "B-XGS-0000",
          product_collection: {
            collection_id: "PC-KST-0000",
            collection_name: null,
          },
          sales_channel_collections: null,
          product_variants: [
            {
              product_variant_id: "PV-JMU-0000",
              business_id: "B-XGS-0000",
              product_id: "P-KXG-0000",
              product_variant_description: "Item",
              product_variant_currency: "KES",
              product_variant_unit_price: 0,
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_expiry_date: null,
              product_variant_quantity: 0,
              product_variant_quantity_type: "GRAM",
              product_variant_stock_levels: {
                available: 0,
                quantity_in_inventory: 0,
                quantity_in_sales_orders: 1,
                quantity_held_in_fulfilment_requests: 0,
                last_updated_date: 1655391003000,
              },
              product_variant_archived: false,
            },
          ],
        },
        {
          product_id: "P-KXG-0000",
          objectID: "P-KXG-0000",
          product_name: "Item",
          product_description: "Item variant",
          product_main_color: null,
          product_archived: false,
          business_id: "B-XGS-0000",
          product_collection: {
            collection_id: "PC-KST-0000",
            collection_name: null,
          },
          sales_channel_collections: null,
          product_variants: [
            {
              product_variant_id: "PV-JMU-0000",
              business_id: "B-XGS-0000",
              product_id: "P-KXG-0000",
              product_variant_description: "Item",
              product_variant_currency: "KES",
              product_variant_unit_price: 0,
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_expiry_date: null,
              product_variant_quantity: 0,
              product_variant_quantity_type: "GRAM",
              product_variant_stock_levels: {
                available: 0,
                quantity_in_inventory: 0,
                quantity_in_sales_orders: 1,
                quantity_held_in_fulfilment_requests: 0,
                last_updated_date: 1655391003000,
              },
              product_variant_archived: false,
            },
          ],
        },
        {
          product_id: "P-KXG-0000",
          objectID: "P-KXG-0000",
          product_name: "Item",
          product_description: "Item variant",
          product_main_color: null,
          product_archived: false,
          business_id: "B-XGS-0000",
          product_collection: {
            collection_id: "PC-KST-0000",
            collection_name: null,
          },
          sales_channel_collections: null,
          product_variants: [
            {
              product_variant_id: "PV-JMU-0000",
              business_id: "B-XGS-0000",
              product_id: "P-KXG-0000",
              product_variant_description: "Item",
              product_variant_currency: "KES",
              product_variant_unit_price: 0,
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_expiry_date: null,
              product_variant_quantity: 0,
              product_variant_quantity_type: "GRAM",
              product_variant_stock_levels: {
                available: 0,
                quantity_in_inventory: 0,
                quantity_in_sales_orders: 1,
                quantity_held_in_fulfilment_requests: 0,
                last_updated_date: 1655391003000,
              },
              product_variant_archived: false,
            },
          ],
        },
      ],
      productsToSubmit: [],
      fulfillmentFees: {
        pricing: {
          pricing_pickups: [
            {
              total_product_value: 0.0,
              pre_adjustments_calculated_fee: null,
              calculated_fee: 0.0,
              currency: "KES",
              order_type: "PICKUP",
              promotion_session_id: null,
              promotion_adjustments: [],
              promotion_notifications: [],
            },
          ],
          pricing_deliveries: [
            {
              total_product_value: 0.0,
              pre_adjustments_calculated_fee: 0.0,
              calculated_fee: 0.0,
              currency: "KES",
              order_type: "DELIVERY",
              promotion_session_id: null,
              promotion_adjustments: [
                {
                  adjustment_type: "COST_OF_FULFILMENT",
                  adjustment_description: "KES 0.0 - KES 300.0",
                  adjustment_subtitle: "12.0% service fee",
                  adjustment_value: 0.0,
                },
                {
                  adjustment_type: "DELIVERY_FEE",
                  adjustment_description: "Delivery Fee",
                  adjustment_subtitle: "Delivery Fee for 3 out of 5 items",
                  adjustment_value: 0.0,
                },
              ],
              promotion_notifications: [],
            },
          ],
          pricing_subtotals: {
            pickup_fee: 0.0,
            fulfilment_fee: 0.0,
            total_fee: 0.0,
          },
        },
        errors: [],
      },
      userDetails: {
        user_id: "U-ALG-1812",
        first_name: "User",
        last_name: "Name",
        user_role: "ROLE_OWNER",
        invitation_status: "INVITATION_ACCEPTED",
        active_status: "ACTIVATED",
        phone_number: "+25422222",
        email: "user@sendyit.com",
        user_access_permissions: [
          {
            permission_id: "CAN_ACCESS_PRODUCTS_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_CREATE_PRODUCTS",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_DELIVERIES_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_CREATE_DELIVERIES",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_CONSIGNMENTS_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_CREATE_CONSIGNMENTS",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_BILLING_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_PAYMENT_OPTIONS_MODULE",
            permission_granted: true,
          },
          {
            permission_id: "CAN_ACCESS_MANAGE_USERS_MODULE",
            permission_granted: true,
          },
        ],
      },
      storageUserDetails: localStorage.userDetails,
      bizDetails: "",
      businessDetails: {},
      notifications: [],
      paymnetMethods: [],
      withDrawalMethods: [
        {
          user_id: "B-AEB-0000",
          pay_method_id: 1,
          pay_method_details: "",
          pay_detail_id: "dd0b183f-30c4-40bb-a69e-000000000",
          status: 1,
          pay_direction: null,
          id: 1370,
          pay_method_name: "M-PESA",
          default: 0,
          psp: "SAFARICOM",
          category: "Mobile Money",
          stk_limit: 150000,
          daily_limit: 300000,
          transaction_limit: 150000,
          minimum_limit: 1,
          withdrawal_limit: 50,
        },
      ],
      withDrawalAmount: "",
      billingCycle: {
        billing_cycle_instance_id: "BC-XCU-0000",
        business_id: "B-AEB-0000",
        cycle_interval_type: "DAILY",
        billing_cycle_start_date: 1655729668000,
        billing_cycle_end_date: 1655830800000,
        active: true,
        grace_period_interval: 2,
        grace_period_interval_type: "HOUR",
        amount_to_charge: 0,
        billable_amount: 0,
        paid_amount: 0,
        order_count: 0,
        paid_status: "PAID",
      },
      billingCycles: [
        {
          billing_cycle_instance_id: "BC-XCU-0000",
          business_id: "B-AEB-0000",
          cycle_interval_type: "DAILY",
          billing_cycle_start_date: 1655729668000,
          billing_cycle_end_date: "",
          active: true,
          grace_period_interval: 2,
          grace_period_interval_type: "HOUR",
          amount_to_charge: 0,
          billable_amount: 0,
          paid_amount: 0,
          order_count: 0,
          paid_status: "PAID",
        },
        {
          billing_cycle_instance_id: "BC-XCU-0000",
          business_id: "B-AEB-0000",
          cycle_interval_type: "DAILY",
          billing_cycle_start_date: 1655729668000,
          billing_cycle_end_date: 1655830800000,
          active: true,
          grace_period_interval: 2,
          grace_period_interval_type: "HOUR",
          amount_to_charge: 0,
          billable_amount: 0,
          paid_amount: 0,
          order_count: 0,
          paid_status: "PAID",
        },
        {
          billing_cycle_instance_id: "BC-XCU-0000",
          business_id: "B-AEB-0000",
          cycle_interval_type: "DAILY",
          billing_cycle_start_date: 1655729668000,
          billing_cycle_end_date: 1655830800000,
          active: true,
          grace_period_interval: 2,
          grace_period_interval_type: "HOUR",
          amount_to_charge: 0,
          billable_amount: 0,
          paid_amount: 0,
          order_count: 0,
          paid_status: "PAID",
        },
      ],
      lineItems: [
        {
          line_item_id: "BCLI-FAR-0000",
          created_date: 1655690826000,
          line_item_type: "ORDER_INVOICE",
          resource_id: "D-UHV-0000",
          amount: 0,
          line_item_title: "Delivery to User",
          line_item_subtitle: "Somewhere",
          line_item_grouping: "DELIVERY",
        },
        {
          line_item_id: "BCLI-FAR-0000",
          created_date: 1655690826000,
          line_item_type: "ORDER_INVOICE",
          resource_id: "D-UHV-0000",
          amount: 0,
          line_item_title: "Delivery to User",
          line_item_subtitle: "Somewhere",
          line_item_grouping: "DELIVERY",
        },
      ],
      checkoutDetails: {
        name: "",
        location: "",
        place: {},
        instructions: "",
        phone: "",
        secPhone: "",
        addPhoneStatus: false,
      },
      achievements: {},
      stockStatistics: {},
      deliveriesStatistics: {},
      consignmentStatistics: {},
      deliveriesStatisticsToday: {},
      consignmentStatisticsToday: {},
      settings: {},
      activePayment: {},
      editedPriceIndex: 0,
      cycleLineItems: [
        {
          line_item_id: "BCLI-RNZV-0000",
          created_date: 1666694385000,
          line_item_type: "ORDER_INVOICE",
          resource_id: "D-ZZQZN-0000",
          amount: 5.5,
          line_item_title: "Delivery to Customer",
          line_item_subtitle: "Thika Road, Nairobi, Kenya",
          line_item_grouping: "DELIVERY",
        },
        {
          line_item_id: "BCLI-RNZV-0000",
          created_date: 1666694385000,
          line_item_type: "ORDER_INVOICE",
          resource_id: "D-ZZQZN-0000",
          amount: 5.5,
          line_item_title: "Delivery to Customer",
          line_item_subtitle: "Thika Road, Nairobi, Kenya",
          line_item_grouping: "DELIVERY",
        },
        {
          line_item_id: "BCLI-RNZV-0000",
          created_date: 1666694385000,
          line_item_type: "ORDER_INVOICE",
          resource_id: "D-ZZQZN-0000",
          amount: 5.5,
          line_item_title: "Delivery to Customer",
          line_item_subtitle: "Thika Road, Nairobi, Kenya",
          line_item_grouping: "DELIVERY",
        },
        {
          line_item_id: "BCLI-RNZV-0000",
          created_date: 1666694385000,
          line_item_type: "ORDER_INVOICE",
          resource_id: "D-ZZQZN-0000",
          amount: 5.5,
          line_item_title: "Delivery to Customer",
          line_item_subtitle: "Thika Road, Nairobi, Kenya",
          line_item_grouping: "DELIVERY",
        },
      ],
      promoCode: "",
      invoice: {
        created_date: 1636456110000,
        order_completed_date: 1636485362000,
        invoice_id: "IV-BSH-0000",
        order_id: "D-WVJ-0000",
        order_summary: {
          order_recipient_name: "Someone",
        },
        order_type: "DELIVERY",
        amount: 0,
        currency: "KES",
        applied_rate: 0,
        invoice_status: "PAYMENT_SUCCESS",
        invoice_adjustments: [],
        means_of_payment: {
          means_of_payment_type: "CARD",
          means_of_payment_id: "0000-74XX-XXXX-0000",
          participant_type: "SELLER",
          participant_id: "B-AEB-0000",
          meta_data: {},
        },
      },
    };
  },
  actions,
  getters,
  mutations,
});
