import { createStore } from "vuex";
import actions from "./actions";
import getters from "./getters";
import mutations from "./mutations";
import { Check, Minus, Remove, Warning } from "@element-plus/icons-vue";

export default createStore({
  namespaced: true,
  state() {
    return {
      mobile: false,
      component: "",
      languages: ["English", "French"],
      defaultLanguage: "English",
      external: [
        "/auth/sign-in",
        "/auth/sign-up",
        "/auth/otp",
        "/external/invite",
      ],
      productStep: 0,
      downloadActions: [
        {
          label: "Excel",
        },
        {
          label: "PDF",
        },
      ],
      deliveryActions: [
        {
          label: "deliveries.getDeliveryCode",
          trigger: false,
        },
        {
          label: "deliveries.rescheduleOrder",
          trigger: false,
        },
        {
          label: "deliveries.cancelOrder",
          trigger: false,
        },
      ],
      tab: "All",
      loader: "loading-text",
      overlay: false,
      activityLog: [
        {
          date: "Thur, 1st May 2022   17:06",
          user: "James Doe",
          action: "Changed the price of Shea butter from KES 500 to KES350",
        },
        {
          date: "Thur, 1st May 2022   15:06",
          user: "Mary Monroe",
          action: "Added a new product called Mango Butter",
        },
        {
          date: "Thur, 1st May 2022   13:06",
          user: "James Doe",
          action: "Changed the price of Shea butter from KES 500 to KES350",
        },
        {
          date: "Thur, 1st May 2022   12:06",
          user: "James Doe",
          action: "Sent a delivery of Shea Butter to Moses Doe",
        },
        {
          date: "Thur, 1st May 2022   11:06",
          user: "James Doe",
          action: "Changed the price of Shea butter from KES 500 to KES350",
        },
        {
          date: "Thur, 1st May 2022   10:06",
          user: "James Doe",
          action: "Changed the price of Shea butter from KES 500 to KES350",
        },
        {
          date: "Thur, 1st May 2022   09:06",
          user: "James Doe",
          action: "Changed the price of Shea butter from KES 500 to KES350",
        },
      ],
      users: [
        {
          name: "James Doe",
          phoneNumber: "+254712634737",
          emailAddress: "James@smartcollections.com",
          status: "Active",
          actions: [
            {
              label: "settings.editUser",
              link: "/settings/edit-user/",
              trigger: "",
            },
            {
              label: "settings.deactivateUser",
              link: "/settings/deactivate-user/",
              trigger: "",
            },
            {
              label: "settings.resendEmail",
              link: "",
              trigger: "resend",
            },
            {
              label: "settings.modifyPermissions",
              link: "/settings/user-permissions",
              trigger: "",
            },
          ],
        },
        {
          name: "Jane Doe",
          phoneNumber: "+254712634737",
          emailAddress: "James1@smartcollections.com",
          status: "Active",
          actions: [
            {
              label: "settings.editUser",
              link: "/settings/edit-user/",
            },
            {
              label: "settings.deactivateUser",
              link: "/settings/deactivate-user/",
            },
            {
              label: "settings.modifyPermissions",
              link: "/settings/user-permissions",
            },
          ],
        },
        {
          name: "Martin Doe",
          phoneNumber: "+254712634737",
          emailAddress: "James2@smartcollections.com",
          status: "Active",
          actions: [
            {
              label: "settings.editUser",
              link: "/settings/edit-user/",
            },
            {
              label: "settings.deactivateUser",
              link: "/settings/deactivate-user/",
            },
            {
              label: "settings.modifyPermissions",
              link: "/settings/user-permissions",
            },
          ],
        },
        {
          name: "Cuz Doe",
          phoneNumber: "+254712634737",
          emailAddress: "James3@smartcollections.com",
          status: "Active",
          actions: [
            {
              label: "settings.editUser",
              link: "/settings/edit-user/",
            },
            {
              label: "settings.deactivateUser",
              link: "/settings/deactivate-user/",
            },
            {
              label: "settings.modifyPermissions",
              link: "/settings/user-permissions",
            },
          ],
        },
        {
          name: "Shyla Doe",
          phoneNumber: "+254712634737",
          emailAddress: "James4@smartcollections.com",
          status: "Active",
          actions: [
            {
              label: "settings.editUser",
              link: "/settings/edit-user/",
            },
            {
              label: "settings.deactivateUser",
              link: "/settings/deactivate-user/",
            },
            {
              label: "settings.modifyPermissions",
              link: "/settings/user-permissions",
            },
          ],
        },
      ],
      invoices: [
        {
          number: "ADFHJFEE34",
          deliveries: "3",
          amount: "KES 340",
          status: "Pending",
          dateSent: "7/7/2022 11:12 AM",
          action: "View",
          link: "/payments/view-invoice",
        },
        {
          number: "ADFHJFEE34",
          deliveries: "3",
          amount: "KES 340",
          status: "Pending",
          dateSent: "7/7/2022 11:12 AM",
          action: "View",
          link: "/payments/view-invoice",
        },
        {
          number: "ADFHJFEE34",
          deliveries: "3",
          amount: "KES 340",
          status: "Pending",
          dateSent: "7/7/2022 11:12 AM",
          action: "View",
          link: "/payments/view-invoice",
        },
        {
          number: "ADFHJFEE34",
          deliveries: "3",
          amount: "KES 340",
          status: "Pending",
          dateSent: "7/7/2022 11:12 AM",
          action: "View",
          link: "/payments/view-invoice",
        },
        {
          number: "ADFHJFEE34",
          deliveries: "3",
          amount: "KES 340",
          status: "Pending",
          dateSent: "7/7/2022 11:12 AM",
          action: "View",
          link: "/payments/view-invoice",
        },
      ],
      invoiceContent: [
        {
          customerInfo: {
            customer: "Delivery to James",
            location: "Windsor Heights",
          },
          products: "Shea Butter & 3 other items",
          dateCompleted: "3/1/2022",
          costOfProducts: "KES 400",
          fulfilmentPrice: "KES 54",
        },
        {
          customerInfo: {
            customer: "Delivery to James",
            location: "Umoja momasa apartments",
          },
          products: "Shea Butter & 3 other items",
          dateCompleted: "3/1/2022",
          costOfProducts: "KES 400",
          fulfilmentPrice: "KES 54",
        },
      ],
      transationHistory: [
        {
          details: {
            icon: "mdi-cash-multiple",
            description: "Payment for 2 orders",
          },
          paymentDetails: "Paid via Mpesa.",
          code: "Transaction code; AE3U83R444",
          datePaid: "7/7/2022 11:12 AM",
          amountPaid: "KES 340",
        },
      ],
      totalDue: "KES 54",
      statements: [
        {
          date: "Friday, 19th Jan 2022",
          amount: "",
          items: [
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Pending payment",
              class: "pending",
              price: "- KES 340",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Pending payment",
              class: "pending",
              price: "- KES 300",
            },
            {
              icon: "mdi-warehouse",
              description: "Delivery to fulfillment centre",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Pending payment",
              class: "pending",
              price: "- KES 0",
            },
          ],
        },
        {
          date: "Thursday, 18th Jan 2022",
          amount: "Kes 1,200",
          items: [
            {
              icon: "mdi-cash-multiple",
              description: "Payment for 2 orders",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "+ KES 760",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 300",
            },
            {
              icon: "mdi-warehouse",
              description: "Delivery to fulfillment centre",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 460",
            },
          ],
        },
        {
          date: "Monday, 15th Jan 2022",
          amount: "Kes 1,200",
          items: [
            {
              icon: "mdi-cash-multiple",
              description: "Payment for 2 orders",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "+ KES 340",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 300",
            },
          ],
        },
        {
          date: "Monday, 15th Jan 2022",
          amount: "Kes 1,200",
          items: [
            {
              icon: "mdi-cash-multiple",
              description: "Payment for 2 orders",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "+ KES 340",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 300",
            },
          ],
        },
        {
          date: "Monday, 15th Jan 2022",
          amount: "Kes 1,200",
          items: [
            {
              icon: "mdi-cash-multiple",
              description: "Payment for 2 orders",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "+ KES 340",
            },
            {
              icon: "mdi-truck-outline",
              description: "Delivery to James",
              items: "Shea Butter & 3 other items",
              date: "7/7/2022 11:12 AM",
              status: "Paid",
              class: "paid",
              price: "- KES 300",
            },
          ],
        },
      ],
      deliveryInfo: {
        name: "James Doe",
        location: "Windsor Heights",
        phoneNumber: "+254712344444",
        instructions: "Leave the package at the door",
        payment: "Mpesa",
      },
      pickupInfo: {
        location: "Windsor Heights",
        phoneNumber: "+254712344000",
        instructions: "Come to Windsor",
      },
      products: {
        name: "Shea Butter and 2 other items",
      },
      deliveries: [
        {
          products: "Shea butter & 3 other items & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
        {
          products: "Shea butter & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
        {
          products: "Shea butter & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
        {
          products: "Shea butter & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
        {
          products: "Shea butter & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
        {
          products: "Shea butter & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
        {
          products: "Shea butter & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
        {
          products: "Shea butter & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
        {
          products: "Shea butter & 3 other items",
          progress: {
            status: "Package is on the way",
            step: "70",
          },
          deliveryDate: {
            date: "Thur, 3/2/2022",
            time: "2pm - 4pm",
          },
          actions: {
            link: "/deliveries/tracking",
            title: "View",
          },
        },
      ],
      data: {
        message: "order.retrieve.success",
        data: {
          seller_name: "Kosgei ltd",
          order_id: "D-YYK-8005",
          country: "KENYA",
          language: "en",
          consolidated: false,
          order_event_status: "event.delivery.rescheduled.by.sendy",
          order_status: "ORDER_RESCHEDULED",
          order_completion_date: null,
          scheduled_delivery_date: 1651219200000,
          estimated_delivery_date: null,
          confirmation_pin: "3414",
          partner_contact_information: null,
          products: [
            {
              product_name: "Black timberland boots.",
              product_variant_description: "Black timberland boots",
              product_unit_price: 66.0,
              product_unit_currency: "KES",
              product_image_link:
                "https://s3.eu-west-1.amazonaws.com/sendy-partner-docs/fulfillment_products/B-KBC-5255_1642591764683_image_picker_A5C1AB9A-1D18-4065-BEE7-9ECF2EC6E421-26512-00000DD592078E05.jpg",
              product_unit_count: 2,
            },
            {
              product_name: "Black timberland boots.",
              product_variant_description: "Option 1",
              product_unit_price: 300.0,
              product_unit_currency: "KES",
              product_image_link:
                "https://s3.eu-west-1.amazonaws.com/sendy-partner-docs/fulfillment_products/B-KBC-5255_1641298024354_image_picker_A053E6C5-E503-4F55-8E35-8CBB8B09B883-25267-00000979B6694B6E.jpg",
              product_unit_count: 2,
            },
          ],
          event_time_line: [
            {
              event_code: "event.delivery.partner.arrived.at.buyer.location",
              event_date: 1636697106000,
              event_notes: null,
            },
            {
              event_code:
                "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
              event_date: 1636697176000,
              event_notes: null,
            },
            {
              event_code: "event.delivery.order.canceled.by.seller",
              event_date: 1636697281000,
              event_notes: null,
            },
            {
              event_code: "event.delivery.failed",
              event_date: 1636698283000,
              event_notes: null,
            },
            {
              event_code: "event.delivery.rescheduled.by.buyer",
              event_date: 1642749240000,
              event_notes: null,
            },
          ],
          destination: {
            name: "Kosgei",
            phone_number: "+254 713 320303",
            delivery_location: {
              description:
                "Sendy Office, Marsabit Plaza 3rd Floor, Ngong Road, Nairobi, Kenya",
              longitude: 36.77289419999999,
              latitude: -1.2998229,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "Leave at the reception",
          },
          rated: false,
        },
        errors: [],
      },
      orderStatuses: [
        "event.delivery.order.created",
        "event.delivery.at.hub.processing.for.delivery",
        "event.delivery.at.hub.partner.assigned",
        "event.delivery.at.hub.waiting.for.partner",
        "event.delivery.partner.enroute.to.hub",
        "event.delivery.partner.arrived.at.hub",
        "event.delivery.partner.pickup.from.hub.confirmed.via.code",
        "event.delivery.partner.enroute.to.buyer.location",
        "event.delivery.partner.arrived.at.buyer.location",
        "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
        "event.delivery.order.canceled.by.seller",
        "event.delivery.order.canceled.by.sendy",
        "event.delivery.failed",
        "event.delivery.rescheduled.by.buyer",
        "event.delivery.rescheduled.by.seller",
        "event.delivery.rescheduled.by.sendy",
      ],
      orderEvents: [
        "deliveries.orderCreated",
        "deliveries.orderProcessed",
        "deliveries.partnerAssigned",
        "deliveries.partnerCollection",
        "deliveries.partnerPickup",
        "deliveries.partnerArrived",
        "deliveries.packageCollected",
        "deliveries.packageInTransit",
        "deliveries.packageArrived",
        "deliveries.deliveryComplete",
        "deliveries.orderCancelled",
        "deliveries.orderFailed",
        "deliveries.partnerIsHere",
        "deliveries.partnerAtDestination",
        "deliveries.deliveryAttempted",
        "deliveries.delay",
        "deliveries.orderCancelledDate",
        "deliveries.arriving",
        "deliveries.deliveryCompleted",
        "deliveries.deliveryCompletedDate",
        "deliveries.preparingDelivery",
        "deliveries.preparedDelivery",
        "deliveries.arrivingSoon",
        "deliveries.rescheduledByBuyer",
        "deliveries.rescheduledBySeller",
        "deliveries.rescheduledBySendy",
        "deliveries.attemptFailed",
        "deliveries.attemptFail",
        "deliveries.orderPlaced",
      ],
      orderTimelines: [
        {
          event: "event.delivery.order.created",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#324ba8", "", ""],
          icons: [Check, Minus, "", ""],
          iconClass: ["el-icon-check", "el-icon-minus", "", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 20, 7, 8],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.at.hub.processing.for.delivery",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#324ba8", "", ""],
          icons: [Check, Minus, "", ""],
          iconClass: ["el-icon-check", "el-icon-minus", "", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 20, 7, 8],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.at.hub.partner.assigned",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", ""],
          icons: [Check, Check, Minus, ""],
          iconClass: ["el-icon-check", "el-icon-minus", "", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "today",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.at.hub.waiting.for.partner",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", ""],
          icons: [Check, Check, Minus, ""],
          iconClass: ["el-icon-check", "el-icon-check", "el-icon-minus", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "today",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.partner.enroute.to.hub",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", ""],
          icons: [Check, Check, Minus, ""],
          iconClass: ["el-icon-check", "el-icon-check", "el-icon-minus", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "today",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.partner.arrived.at.hub",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", ""],
          icons: [Check, Check, Minus, ""],
          iconClass: ["el-icon-check", "el-icon-check", "el-icon-minus", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "today",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.partner.pickup.from.hub.confirmed.via.code",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", ""],
          icons: [Check, Check, Minus, ""],
          iconClass: ["el-icon-check", "el-icon-check", "el-icon-minus", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "today",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.partner.enroute.to.buyer.location",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", ""],
          icons: [Check, Check, Minus, ""],
          iconClass: ["el-icon-check", "el-icon-check", "el-icon-minus", ""],
          showDriver: [false, false, true, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "today",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 21, 22, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.partner.arrived.at.buyer.location",
          steps: [0, 1, 8, 9],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", ""],
          icons: [Check, Check, Minus, ""],
          iconClass: ["el-icon-check", "el-icon-check", "el-icon-minus", ""],
          showDriver: [false, false, true, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "today",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 21, 12, 18],
          showReschedule: [false, false, false, false],
        },
        {
          event:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          steps: [0, 1, 7, 9],
          colors: ["#EE7D00", "#EE7D00", "#EE7D00", "#EE7D00"],
          icons: [Check, Check, Check, Check],
          iconClass: [
            "el-icon-check",
            "el-icon-check",
            "el-icon-check",
            "el-icon-check",
          ],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "completed",
              status: true,
              format: "ddd, MMM Do",
            },
          ],
          titles: [28, 21, 13, 19],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.order.canceled.by.seller",
          steps: [0, 10],
          colors: ["#EE7D00", "#EE7D00"],
          icons: [Check, Check],
          iconClass: ["el-icon-check", "el-icon-check"],
          showDriver: [false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
          ],
          titles: [28, 16],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.order.canceled.by.sendy",
          steps: [0, 11],
          colors: ["#EE7D00", "#EE7D00"],
          icons: [Check, Check],
          iconClass: ["el-icon-check", "el-icon-check"],
          showDriver: [false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
          ],
          titles: [28, 16],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.failed",
          steps: [0, 1, 7, 12, 9],
          colors: ["#EE7D00", "#EE7D00", "#EE7D00", "#9B101C", "#909399"],
          icons: [Check, Check, Check, Remove, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-check",
            "el-icon-check",
            "el-icon-remove",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
          ],
          titles: [28, 21, 8, 26, 18],
          showReschedule: [false, false, false, true, false],
        },
        {
          event: "event.delivery.rescheduled.by.buyer",
          steps: [0, 13, 1, 7, 9],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", "", ""],
          icons: [Check, Check, Minus, "", ""],
          iconClass: [
            "el-icon-check",
            "el-icon-check",
            "el-icon-minus",
            "",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            { status: false },
          ],
          titles: [28, 23, 1, 7, 18],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.rescheduled.by.seller",
          steps: [0, 14, 1, 7, 9],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", "", ""],
          icons: [Check, Check, Minus, "", ""],
          iconClass: [
            "el-icon-check",
            "el-icon-check",
            "el-icon-minus",
            "",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            { status: false },
          ],
          titles: [28, 24, 1, 7, 18],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.rescheduled.by.sendy",
          steps: [0, 15, 1, 7, 9],
          colors: ["#EE7D00", "#EE7D00", "#324ba8", "", ""],
          icons: [Check, Check, Minus, "", ""],
          iconClass: [
            "el-icon-check",
            "el-icon-check",
            "el-icon-minus",
            "",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            { status: false },
          ],
          titles: [28, 25, 1, 7, 18],
          showReschedule: [false, false, false, false, false],
        },
      ],
      rescheduledOrderTimelines: [
        {
          event: "event.delivery.order.created",
          steps: [0, 1, 7, 8],
          colors: ["#EE7D00", "#324ba8", "", ""],
          icons: [Check, Minus, "", ""],
          iconClass: ["el-icon-check", "el-icon-minus", "", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "dddd",
            },
          ],
          titles: [28, 20, 7, 8],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.at.hub.processing.for.delivery",
          steps: [0, 12, 13, 1, 8],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#324ba8", ""],
          icons: [Check, Warning, Check, Minus, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-minus",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 20, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.at.hub.partner.assigned",
          steps: [0, 12, 13, 7, 8],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#324ba8", ""],
          icons: [Check, Warning, Check, Minus, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-minus",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.at.hub.waiting.for.partner",
          steps: [0, 12, 13, 7, 8],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#324ba8", ""],
          icons: [Check, Warning, Check, Minus, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-minus",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.partner.enroute.to.hub",
          steps: [0, 12, 13, 7, 8],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#324ba8", ""],
          icons: [Check, Warning, Check, Minus, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-minus",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.partner.arrived.at.hub",
          steps: [0, 12, 13, 7, 8],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#324ba8", ""],
          icons: [Check, Warning, Check, Minus, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-minus",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.partner.pickup.from.hub.confirmed.via.code",
          steps: [0, 12, 13, 7, 8],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#324ba8", ""],
          icons: [Check, Warning, Check, Minus, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-minus",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.partner.enroute.to.buyer.location",
          steps: [0, 12, 13, 7, 8],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#324ba8", ""],
          icons: [Check, Warning, Check, Minus, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-minus",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.partner.arrived.at.buyer.location",
          steps: [0, 12, 13, 8, 9],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#324ba8", ""],
          icons: [Check, Warning, Check, Minus, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-minus",
            "",
          ],
          showDriver: [false, false, false, true, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 12, 18],
          showReschedule: [false, false, false, false, false],
        },
        {
          event:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          steps: [0, 12, 13, 7, 9],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", "#EE7D00", "#EE7D00"],
          icons: [Check, Warning, Check, Check, Check],
          iconClass: [
            "el-icon-check",
            "el-icon-warning",
            "el-icon-check",
            "el-icon-check",
            "el-icon-check",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "completed",
              status: true,
              format: "ddd, MMM Do",
            },
          ],
          titles: [28, 27, 23, 7, 19],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: "event.delivery.order.canceled.by.seller",
          steps: [0, 10],
          colors: ["#EE7D00", "#EE7D00"],
          icons: [Check, Check],
          iconClass: ["el-icon-check", "el-icon-check"],
          showDriver: [false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
          ],
          titles: [28, 16],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.order.canceled.by.sendy",
          steps: [0, 11],
          colors: ["#EE7D00", "#EE7D00"],
          icons: [Check, Check],
          iconClass: ["el-icon-check", "el-icon-check"],
          showDriver: [false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
          ],
          titles: [28, 16],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.failed",
          steps: [0, 1, 7, 12, 9],
          colors: ["#EE7D00", "#EE7D00", "#EE7D00", "#9B101C", "#909399"],
          icons: [Check, Check, Check, Remove, ""],
          iconClass: [
            "el-icon-check",
            "el-icon-check",
            "el-icon-check",
            "el-icon-remove",
            "",
          ],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            { status: false },
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
          ],
          titles: [28, 21, 8, 26, 18],
          showReschedule: [false, false, false, true, false],
        },
        {
          event: "event.delivery.rescheduled.by.buyer",
          steps: [0, 12, 13, 9],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", ""],
          icons: [Check, Warning, Check, ""],
          iconClass: ["el-icon-check", "el-icon-warning", "el-icon-check", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
          ],
          titles: [28, 27, 23, 18],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.rescheduled.by.seller",
          steps: [0, 12, 14, 9],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", ""],
          icons: [Check, Warning, Check, ""],
          iconClass: ["el-icon-check", "el-icon-warning", "el-icon-check", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
          ],
          titles: [28, 27, 24, 18],
          showReschedule: [false, false, false, false],
        },
        {
          event: "event.delivery.rescheduled.by.sendy",
          steps: [0, 12, 15, 9],
          colors: ["#EE7D00", "#9B101C", "#EE7D00", ""],
          icons: [Check, Warning, Check, ""],
          iconClass: ["el-icon-check", "el-icon-warning", "el-icon-check", ""],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: "timeline",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
            {
              type: "scheduled",
              status: true,
              format: "ddd, MMM Do",
            },
            { status: false },
          ],
          titles: [28, 27, 25, 18],
          showReschedule: [false, false, false, false],
        },
      ],
      dashboardSelectedTab: "To your Customers",
      inventorySelectedTab: "All",
      stockSelectedTab: "Overview",
      selectedProducts: [],
      sendProductsRoute: "",
      productLists: {
        message: "product.list.success",
        data: {
          products: [
            {
              business_id: "B_ASD123",
              product_id: "P_ASD1234",
              product_name: "Shea Butter",
              product_description: "Smooth shear butter",
              sales_channel_collections: [
                {
                  collection_id: "string",
                  collection_name: "string",
                },
              ],
              product_link:
                "https://images.sendyit.com/fulfilment/seller/shea.png",
              available: "23",
              committed: "23",
              incoming: "4",
              product_currency: "KES",
              product_price: 450,
            },
            {
              business_id: "B_ASD123",
              product_id: "P_ASD1234",
              product_name: "Leather Bags",
              product_description: "Good quality Leather Bags",
              sales_channel_collections: [
                {
                  collection_id: "string",
                  collection_name: "string",
                },
              ],
              product_link:
                "https://images.sendyit.com/fulfilment/seller/shea.png",
              available: "0",
              committed: "0",
              incoming: "0",
              product_currency: "KES",
              product_price: 450,
            },
            {
              business_id: "B_ASD123",
              product_id: "P_ASD1234",
              product_name: "Ceramic Cup",
              product_description: "Hand made ceramic cups",
              product_link:
                "https://images.sendyit.com/fulfilment/seller/shea.png",
              product_variants: [
                {
                  business_id: "B_ASD123",
                  product_id: "P_ASD123",
                  product_variant_id: "PV_ASD123",
                  product_variant_description: "Fortified Cup",
                  product_variant_currency: "KES",
                  product_variant_unit_price: 400,
                  product_variant_quantity: 30,
                  product_variant_quantity_type: "ml",
                  product_variant_image_link:
                    "https://images.sendyit.com/fulfilment/seller/shirts.png",
                  product_variant_expiry_date: 123456789,
                  product_variant_stock_levels: {
                    available: 3,
                    quantity_in_inventory: 1,
                    quantity_in_sales_orders: 0,
                  },
                },
                {
                  business_id: "B_ASD123",
                  product_id: "P_ASD123",
                  product_variant_id: "PV_ASD123",
                  product_variant_description: "Fortified Cup",
                  product_variant_currency: "KES",
                  product_variant_unit_price: 400,
                  product_variant_quantity: 130,
                  product_variant_quantity_type: "ml",
                  product_variant_image_link:
                    "https://images.sendyit.com/fulfilment/seller/shirts.png",
                  product_variant_expiry_date: 123456789,
                  product_variant_stock_levels: {
                    available: 3,
                    quantity_in_inventory: 0,
                    quantity_in_sales_orders: 0,
                  },
                },
              ],
              sales_channel_collections: [
                {
                  collection_id: "string",
                  collection_name: "string",
                },
              ],
              available: "23",
              committed: "25",
              incoming: "7",
              product_currency: "KES",
              product_price: 450,
            },
          ],
        },
      },
    };
  },
  actions,
  getters,
  mutations,
});
