module.exports = {
  DOCKER_ENV: "beta",
  NODE_ENV: "production",
  AUTH: "https://auth.sendyit.com/",
  GOOGLE_API_KEY: "AIzaSyBr3G1ZoEidlWAw_NOO11NZsVidPuF6zeo",
  GOOGLE_API_KEY_TEST: "AIzaSyC4UV3vk4qedVcCXDdpY7ZBNb4IQAM4vY8",
  GOOGLE_CLIENT_ID:
    "724697801657-96bbmn0plsro60t4rg2eekvnbfrfnqvb.apps.googleusercontent.com",
  VAPIDKEY:
    "BGNlgSsJAfNM7suOwAm0LyVX7H5GCB9lUosFfOQy99Qrhr7fpPGE2xd5h7qekXL0WYwIf2K26CCMz3wWMiG49jY",
  ELASTIC_APM_SERVICE_NAME: '"seller-web-app"',
  ELASTIC_APM_SERVICE_VERSION: '"1.0.0"',
  ELASTIC_APM_SERVER_URL: '"https://apm.sendyit.com:443"',
  ELASTIC_APM_ENVIRONMENT: '"production"',
  ELASTIC_APM_DISTRIBUTED_TRACING_ORIGINS: '"https://auth.sendyit.com"',
  ALGOLIA_APP_ID: "YGZO0B7NVS",
  ALGOLIA_API_KEY: "d19d556ce4b0b3897d5c8956e43428c2",
  ALGOLIA_INDEX_NAME: "production_fulfillment",
  ALGOLIA_INDEX_NAME_ORDERS: "production_fulfillment_orders",
  FULFILMENT_SERVER: "https://auth.sendyit.com/fulfilment/v1/",
  SELLER_FULFILLMENT_SERVER:
    "https://fulfillment-biz-logic-service-dev.sendyit.com/v1/",
  VUE_APP_BASE_URL: "https://auth.sendyit.com/payment-gateway",
  VUE_APP_VGS_VAULT_ID: "tntrt5wb0ic",
  VUE_APP_VGS_ENVIRONMENT: "live",
  EXTREME_IP_KEY: "dmmw1HciGEhld0FiG2ID",
  MERCHANT_GATEWAY: "https://merchant-gateway-test.sendyit.com/",
  RND_ORDER_PLACEMENT: "https://rnd-order-placement.sendyit.com/",
  FULFILMENT_API: "https://fulfillment-api-test.sendyit.com/",
  SOLR_RIDER_SEARCH: "https://auth.sendyit.com/solr/riders/",
};
