const placeholders = {
  data() {
    return {
      placeHolderDeliveries: [
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
      ],
      placeholderConsignments: [
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
        {
          order_id: "D-AIZ-0000",
          erp_document_number: "SORD000000",
          order_status: "ORDER_COMPLETED",
          rejection_status: null,
          created_date: 1644570481000,
          updated_date: 1644570629000,
          order_event_status:
            "event.delivery.partner.submitted.items.to.buyer.confirmed.via.code",
          business_id: "B-XGS-0000",
          scheduled_date: 1644652800000,
          completed_date: 1644570629000,
          confirmation_pin: "0000",
          products: [
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0336",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
            {
              product_id: "P-KXG-0000",
              product_variant_id: "PV-JMU-0000",
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_description: "Item",
              line_item_id: "VLI-LBS-0000",
              quantity: 1,
              rejected_quantity: 0,
              received_quantity: 1,
              unit_price: 50,
              currency: "KES",
            },
          ],
          destination: {
            name: "Some User",
            phone_number: "+2547000000000",
            delivery_location: {
              description: "Somewhere",
              longitude: 0.000001,
              latitude: 0.000001,
              region: null,
            },
            house_location: "Not set",
            delivery_instructions: "",
          },
          invoice_summary: {
            invoice_id: "IV-USN-0000",
            total_cost: 0,
            fulfillment_fee: 0,
            applied_rate: 0,
            currency: "KES",
            means_of_payment: {
              means_of_payment_type: "CARD",
              means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
              participant_type: "SELLER",
              participant_id: "B-XGS-0000",
              meta_data: {},
            },
          },
          failed_attempt_count: 0,
          rated: false,
          sales_channel_id: null,
          delegated_means_of_payment_collection: [],
          fulfilment_cost_means_of_payment: {
            means_of_payment_type: "CARD",
            means_of_payment_id: "XXXX-XXXX-XXXX-XXXX",
            participant_type: "SELLER",
            participant_id: "B-XGS-0000",
            meta_data: {},
          },
          sale_of_goods_means_of_payment: null,
          sale_of_goods_means_of_remuneration: null,
          sale_of_goods_invoice: null,
          sale_of_goods_payments: [],
          handshake_policy: null,
          rejection_policy: null,
        },
      ],
      placeholderOnDemandDeliveries: [
        {
          order_id: "P2P-ZKJBD-04923",
          order_status: "ORDER_RECEIVED",
          order_type: "POINT_TO_POINT",
          created_date: 1678416647000,
          business_id: "B-AEB-9648",
          updated_date: 1678416647000,
          scheduled_date: 1678416646000,
          instructions: [
            {
              name: "Jim Wanjogu",
              phone_number: "+254723333444",
              secondary_phone_number: "string",
              delivery_location: {
                description: "Garden City, Thika Road, Nairobi",
                longitude: 36.9218576,
                latitude: -1.1927458,
                zone_name: null,
                zone_id: null,
              },
              house_location: "House 3R ,4th Floor, Airpods Apartments",
              delivery_instructions: "Leave at the door",
              actions: [
                {
                  package_uuid: "12345678",
                  package_description: "Bananas",
                  action_type: "PICK_PACKAGE",
                },
              ],
            },
            {
              name: "Jim Wanjogu",
              phone_number: "+254723333444",
              secondary_phone_number: "string",
              delivery_location: {
                description: "Garden City, Thika Road, Nairobi",
                longitude: 36.80885626951856,
                latitude: -1.2701766584461716,
                zone_name: null,
                zone_id: null,
              },
              house_location: "House 3R ,4th Floor, Airpods Apartments",
              delivery_instructions: "Leave at the door",
              actions: [
                {
                  package_uuid: "12345678",
                  package_description: "Bananas",
                  action_type: "DROP_PACKAGE",
                },
              ],
            },
          ],
        },
      ],
      placeholderProducts: [
        {
          product_id: "P-KXG-0000",
          objectID: "P-KXG-0000",
          product_name: "Item",
          product_description: "Item variant",
          product_main_color: null,
          product_archived: false,
          business_id: "B-XGS-0000",
          product_collection: {
            collection_id: "PC-KST-0000",
            collection_name: null,
          },
          sales_channel_collections: null,
          product_variants: [
            {
              product_variant_id: "PV-JMU-0000",
              business_id: "B-XGS-0000",
              product_id: "P-KXG-0000",
              product_variant_description: "Item",
              product_variant_currency: "KES",
              product_variant_unit_price: 0,
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_expiry_date: null,
              product_variant_quantity: 0,
              product_variant_quantity_type: "GRAM",
              product_variant_stock_levels: {
                available: 0,
                quantity_in_inventory: 0,
                quantity_in_sales_orders: 1,
                quantity_held_in_fulfilment_requests: 0,
                last_updated_date: 1655391003000,
              },
              product_variant_archived: false,
            },
          ],
        },
        {
          product_id: "P-KXG-0000",
          objectID: "P-KXG-0000",
          product_name: "Item",
          product_description: "Item variant",
          product_main_color: null,
          product_archived: false,
          business_id: "B-XGS-0000",
          product_collection: {
            collection_id: "PC-KST-0000",
            collection_name: null,
          },
          sales_channel_collections: null,
          product_variants: [
            {
              product_variant_id: "PV-JMU-0000",
              business_id: "B-XGS-0000",
              product_id: "P-KXG-0000",
              product_variant_description: "Item",
              product_variant_currency: "KES",
              product_variant_unit_price: 0,
              product_variant_image_link:
                "https://images.sendyit.com/fulfilment/seller/shirts.png",
              product_variant_expiry_date: null,
              product_variant_quantity: 0,
              product_variant_quantity_type: "GRAM",
              product_variant_stock_levels: {
                available: 0,
                quantity_in_inventory: 0,
                quantity_in_sales_orders: 1,
                quantity_held_in_fulfilment_requests: 0,
                last_updated_date: 1655391003000,
              },
              product_variant_archived: false,
            },
          ],
        },
      ],
      placeholderBillingCycles: [
        {
          billing_cycle_instance_id: "BC-XCU-0000",
          business_id: "B-AEB-0000",
          cycle_interval_type: "DAILY",
          billing_cycle_start_date: 1655729668000,
          billing_cycle_end_date: 1655830800000,
          active: true,
          grace_period_interval: 2,
          grace_period_interval_type: "HOUR",
          amount_to_charge: 0,
          billable_amount: 0,
          paid_amount: 0,
          order_count: 0,
          paid_status: "PAID",
        },
        {
          billing_cycle_instance_id: "BC-XCU-0000",
          business_id: "B-AEB-0000",
          cycle_interval_type: "DAILY",
          billing_cycle_start_date: 1655729668000,
          billing_cycle_end_date: 1655830800000,
          active: true,
          grace_period_interval: 2,
          grace_period_interval_type: "HOUR",
          amount_to_charge: 0,
          billable_amount: 0,
          paid_amount: 0,
          order_count: 0,
          paid_status: "PAID",
        },
        {
          billing_cycle_instance_id: "BC-XCU-0000",
          business_id: "B-AEB-0000",
          cycle_interval_type: "DAILY",
          billing_cycle_start_date: 1655729668000,
          billing_cycle_end_date: 1655830800000,
          active: true,
          grace_period_interval: 2,
          grace_period_interval_type: "HOUR",
          amount_to_charge: 0,
          billable_amount: 0,
          paid_amount: 0,
          order_count: 0,
          paid_status: "PAID",
        },
      ],
      placeholderLineItems: [
        {
          line_item_id: "BCLI-FAR-0000",
          created_date: 1655690826000,
          line_item_type: "ORDER_INVOICE",
          resource_id: "D-UHV-0000",
          amount: 0,
          line_item_title: "Delivery to User",
          line_item_subtitle: "Somewhere",
          line_item_grouping: "DELIVERY",
        },
        {
          line_item_id: "BCLI-FAR-0000",
          created_date: 1655690826000,
          line_item_type: "ORDER_INVOICE",
          resource_id: "D-UHV-0000",
          amount: 0,
          line_item_title: "Delivery to User",
          line_item_subtitle: "Somewhere",
          line_item_grouping: "DELIVERY",
        },
      ],
      placeholderOrderTimelines: [
        {
          event_date: 1647870724000,
          event_code: "EVENT_PICKUP_ORDER_CREATED",
          translated_event_code: "summarised.event.pickup.order.created",
          notes: "",
          event_tense: "FUTURE",
          metadata: {},
        },
        {
          event_date: 1647870724000,
          event_code: "EVENT_PICKUP_WAITING_FOR_PARTNER",
          translated_event_code: "summarised.event.pickup.waiting.for.partner",
          notes: "",
          event_tense: "FUTURE",
          metadata: {},
        },
        {
          event_date: 1647870724000,
          event_code: "EVENT_PICKUP_PARTNER_ARRIVED_AT_PICKUP_LOCATION",
          translated_event_code:
            "summarised.event.pickup.partner.arrived.at.pickup.location",
          notes: "",
          event_tense: "FUTURE",
          metadata: {
            shipping_agent: null,
          },
        },
        {
          event_date: 1647870724000,
          event_code:
            "EVENT_PICKUP_PARTNER_SUBMITTED_ITEMS_AT_HUB_CONFIRMED_VIA_CODE",
          translated_event_code:
            "summarised.event.pickup.partner.submitted.items.at.hub.confirmed.via.code",
          notes: null,
          event_tense: "FUTURE",
          metadata: {},
        },
      ],
      placeHolderFees: {
        pricing: {
          pricing_pickups: [
            {
              total_product_value: 0.0,
              pre_adjustments_calculated_fee: null,
              calculated_fee: 0.0,
              currency: "KES",
              order_type: "PICKUP",
              promotion_session_id: null,
              promotion_adjustments: [],
              promotion_notifications: [],
            },
          ],
          pricing_deliveries: [
            {
              total_product_value: 0.0,
              pre_adjustments_calculated_fee: 0.0,
              calculated_fee: 0.0,
              currency: "KES",
              order_type: "DELIVERY",
              promotion_session_id: null,
              promotion_adjustments: [
                {
                  adjustment_type: "COST_OF_FULFILMENT",
                  adjustment_description: "KES 0.0 - KES 300.0",
                  adjustment_subtitle: "12.0% service fee",
                  adjustment_value: 0.0,
                },
                {
                  adjustment_type: "DELIVERY_FEE",
                  adjustment_description: "Delivery Fee",
                  adjustment_subtitle: "Delivery Fee for 3 out of 5 items",
                  adjustment_value: 0.0,
                },
              ],
              promotion_notifications: [],
            },
          ],
          pricing_subtotals: {
            pickup_fee: 0.0,
            fulfilment_fee: 0.0,
            total_fee: 0.0,
          },
        },
        errors: [],
      },
    };
  },
};
export default placeholders;
